name: Deploy Elm site to GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup Elm
      uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1

    - name: Install dependencies
      run: npm install

    - name: Build
      run: elm make src/Main.elm --optimize --output=docs/elm.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs